### ISSUE TITLE
[Task] 클라이언트 초기설정하기

### ISSUE THREAD

**Issue by HyeongAn** [codestates/ModuMarket#10]
### ISSUE
* Group:  client
* Type: feature
* Detail: 모듈 설치 등 기본 설정하기

### TODO
1. [x]  모듈설치
2. [x] 파일 / 폴더 나누기
3. [x] **전체적인 컴포넌트 구성 나누기** 
**(site map처럼 기능을 세세하게 적어 컴포넌트를 분류해 놓기, hooks를 이용시 해당 컨테이너에서 useState 사용하는 이유에 대한 명확한 설명이 필요.)**
5. [x] 함수명에 대한 규칙 (적절한 동사를 붙여 사용할 수 있도록 하기)

### Estimated time
> 
* Estimated time: E: 3h
* Group : client
* Sprint: Sprint1
* Urgency: High
