### ISSUE TITLE
[Task] 프론트 홈페이지 구현

### ISSUE THREAD

**Issue by HyeongAn** [codestates/ModuMarket#12]
### ISSUE
* Group:  client
* Type: feature
* Detail: 첫 홈 페이지 구현

### TODO
1. [x]  게시판 버튼
2. [x]  로고 클릭으로 홈으로 가질 수 있도록
3. [x]  로그인 버튼
4. [x] 마이페이지 버튼 (내정보수정, 나의공고글, 참여공고글)
5. [x] 서비스 소개글 (소개 사진 넣기)
6. [x] 네비게이션 바, footer 바 컴포넌트 구현

### Estimated time

* Group : client
* Sprint: Sprint2
* Urgency: High
