### ISSUE TITLE
[Task] 프론트 공고글 컴포넌트 구현

### ISSUE THREAD

**Issue by HyeongAn** [codestates/ModuMarket#18]
### ISSUE
* Group:  client
* Type: feature
* Detail: 공고글 컴포넌트 구현하기

### TODO
1. [x]  수정 버튼 만들기
2. [x]  삭제 버튼 만들기
3. [x]  채팅하기 버튼 만들기
4. [x] 참가 / 참가 취소 버튼 만들기
5. [x] 수정하시겠습니까 모달창 만들기
6. [x] 참가 완료 모달창 만들기
7. [x] 참가 취소 모달창 만들기
8. [x] 삭제하시겠습니까 모달창 만들기 
(삭제할 수 있는 기준을 정해야함. 참가인원을 최소인원으로 하여 초과 되면 삭제 할 수 없는 방향으로)
9. [x] 위치 API 구현
10. [x] 수정하기를 누르면 기존에 입력했던 공고글 등록하기 창이 뜨고 안에는 입력했던 데이터 보여주기
11. [ ] 남은시간 타이머 구현 (도전)

### Estimated time

* Group : client
* Sprint: Sprint2
* Urgency: High
