### ISSUE TITLE
[Task] 서버 초기세팅

### ISSUE THREAD

**Issue by cookiemiro** [codestates/ModuMarket#22]
### ISSUE
* Group:  server
* Detail: 

### TODO

1. [x] 메인페이지 route 연결
2. [x] 로그인 route 연결
3. [x] 회원가입 route 연결
4. [x] 공고 게시판 route 연결
5. [x] 마이페이지 route 연결
6. [x] 채팅창 route 연결
7. [x] MongoDB 연결

### Estimated time
> 8h
