### ISSUE TITLE
[Task] API 문서 작성하기

### ISSUE THREAD

**Issue by HyeongAn** [codestates/ModuMarket#8]
### ISSUE
* Group:  sr
* Type: feature
* Detail: API 문서 작성하기

### TODO
1. [x]  사용처 나누기
2. [x]  전달할 데이터와 메소드 나누기
3. [x]  엔드포인트 나누기
4. [x] 응답코드(응답 메세지) 정하기
5. [x] 예상 응답 데이터 정하기
6. [x] 헤더에 들어올 값 정하기

### Estimated time
> 
* Estimated time: E: 4h
* Group : client, server
* Sprint: Sprint1
* Urgency: High
